### ISSUE TITLE
Putting shinobu on the App Store

### ISSUE THREAD

**Issue by jallbrit** [Nyx0uf/shinobu#2]
I see in the `README.md` that money is a limiting factor in putting this on the app store. However, solutions such as [opencollective.com](opencollective.com) exist to help crowdfund a project like this, and be transparent about how the money is spent. If we were able to collect $100, would someone be willing to administer the process of putting this on the App Store?

**Comment by snshn** [comment]
I concur with the point mentioned above. Also, have you thought about keeping the code base open-source, but putting it up on the app store and requiring a small payment (e.g. $1.00 to install it or to hide the ads)? Many apps inferior to Shinobu do this and manage to make money; it feels unfair that good software remains unknown. Letting users download and build it themselves (which would not feature any ads and would not be considered "cracking it") could be a good option, so that it's sort of you getting reimbursed for putting it online and having to deal with Apple's shenanigans.

**Comment by Nyx0uf** [comment]
Did this in the past, open-source code and paid app on the App store, I managed to get ~2 years paid.
It's very time consuming because you have to deal with the stupid and unfair validation process which is a pain.
Then, once people start to pay they expect updates, features... (which is totally fair). I don't want to spend time implementing things I do not care, remember that originally I'm doing this app on my free time for my own personal needs.
